version: '3.8'

services:
  bitespeed-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/tmp/contacts.db
      - PORT=8080
    volumes:
      - db_data:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data: